### ISSUE TITLE
Remove Ads

### ISSUE THREAD

**Issue by manavortex** [matt-kruse/SocialFixer#16]
Hello there, 

found this: https://hackernoon.com/how-i-get-rid-of-the-new-sponsored-facebook-posts-138d013f4bbe

fyi :)

**Comment by mjeveritt** [comment]
@manavortex, perhaps you would like to join our support group and developer group via Facebook (ironic, I know) and we can see if we could potentially put some of your talents/skills to good use :smiley:

**Comment by siffegh** [comment]
@mjeveritt, I don't think mannvortex wrote that script :-)

**Comment by siffegh** [comment]
I tried the script. It hid only one out of four sponsored posts.

**Comment by mjeveritt** [comment]
My bad .. here was I being optimistic again ..

**Comment by manavortex** [comment]
Pity, I just stumbled upon it and thought it might be worth a try :)
