### ISSUE TITLE
Who of my friends live in X-town?

### ISSUE THREAD

**Issue by l-g** [matt-kruse/SocialFixer#5]
Years ago Facebook had a feature that allowed me to search for my friends who listed X-Town as their hometown. This feature is long gone. Couldn't SF recreate it? Scan my friend list and then display everyone in my friends list's hometown on a map or something? This would gather already data I already have access to but in a more convenient way.

Great feature when you are traveling: who lives in the town I am visiting next week?

**Comment by siffegh** [comment]
(SFx Support Team) SFx cannot do that.

**Comment by l-g** [comment]
Why not? You already keep track of my friends. Skip the map-thing, just present a list or something.

**Comment by siffegh** [comment]
Because SFx doesn't have access to that level of data.

**Comment by l-g** [comment]
What do you mean? SFX has access to the same data as the user, or at least could request that.

**Comment by siffegh** [comment]
No, it doesn't. SFx doesn't use the FB API. It's very limited as to what data it can access. Besides, what you request is beyond the scope of SFx, which basically is to filter posts, track friending/unfriending, and customize the appearance of FB.

**Comment by l-g** [comment]
How about we ask Mr Kruse about that?

**Comment by mjeveritt** [comment]
You can ask all you like. Matt's time is severely limited, and as for adding new code to specifically request additional data from Facebook and process it, and add it in a secure and maintainable way to SocialFixer (you think we don't have enough to deal with just keeping up with minor code changes? The original Friend Tracker had to be dropped, and the current one is precarious at best!) ...
Seriously, knock it off, and give us a break. Thanks.

**Comment by mjeveritt** [comment]
Thanks for joining us on the 'dark side' btw @siffegh :smiley:

**Comment by l-g** [comment]
The stupidest response ever. How about asking your users a question whether this feature would be popular or not? That is the right way to handle a request like this.

**Comment by mjeveritt** [comment]
Or we could ban you from trolling this repository.

We have an approximate 0.6 developers and 3-4 volunteer user support agents on this project. Perhaps you'd respect that the decisions of the Team are final, and not subject to renegotiation, like most other 'Free' software projects. That you have a product which you don't have to pay for, doesn't give you the right to demand anything...

**Comment by l-g** [comment]
Since you are not the 0.6 developer maybe you should STFU and let someone who can code make the decision?

And you don't know the meaning of the word "trolling". Not agreeing with someone is not trolling. Besides. it is no human right to have the last word.

**Comment by matt-kruse** [comment]
@l-g This is, in theory, possible. In fact, the "Friends List" tab of "Friend Manager" was actually built with the intention of adding more fields, and being able to filter by them. Hometown could certainly be one of them.
The problem is, there is no way that I know of to get this data in bulk. SFX would need to visit each friend's page individually and scrape the data. This is absolutely possible, but quite tedious, time-consuming, and potentially fragile. If done too rapidly, Facebook could detect it and decide that this is a robot harvesting data, and lock the user's account. I just don't know for sure.
So, I'm very hesitant to add this, at least right now. I would be open to exploring it.

**Comment by l-g** [comment]
Great. I understand your concern. Sounds like it would be better as an external (to SFX) solution. Something like a Greasemonkey script you could run from time to time when you would like to figure if you know someone in the town you are going to visit next week or so.
